### ISSUE TITLE
some problems about MS-TCT on charades dataset

### ISSUE THREAD

**Issue by Wyz2927** [dairui01/MS-TCT#3]
I have some questions about MS-TCT. I try to use the published code to train a MS-TCT model on charades dataset, but get a much lower map value than the paper reported. I only get 19.8750 map on charades dataset. I want to know if there exist some tricks when training the model? And the following is my training set. 
 
![image](https://user-images.githubusercontent.com/96815275/197968917-c854b3bb-f89c-428e-abab-271a136711ca.png)

 
![image](https://user-images.githubusercontent.com/96815275/197968957-68ba1568-15bc-4f87-9be1-d794b79ec666.png)

and my training log is as follow:
![image](https://user-images.githubusercontent.com/96815275/197969201-fd860a97-74d9-4a4f-8ad5-ca909d13b9cf.png)
it seems that the model is easy to be over-fitting.

**Comment by dairui01** [comment]
There is no trick for training the model in the code. If all the hyperparameters are the same, then I think the issue lies in the low-quality I3D features. As the MS-TCT inputs the I3D features, thus the feature quality is critical. 
In our work, we follow exactly the same as this repository to extract the feature: [https://github.com/piergiaj/pytorch-i3d](https://github.com/piergiaj/pytorch-i3d)

Note that: You can utilize directly their charades pre-trained model to extract the features. However, please do not change any terms relevant to the window size in the original code of I3D feature extraction. This change may hamper the final feature quality. Moreover, please utilize the RGB frames at 24 fps frame version rather than the provided 480p version from their website. Different video resolutions can also cause a difference in the final result.
